Adding IdentityMap and ComposedMap classes
MeasureTransport/MParT pull request #243
Opened 2022-09-22 16:35 UTC by michael-c-brennan

IdentityMap: Implements rectangular maps of the form $I(x_1, x_2) = x_2$

ComposedMap: Given square maps $T_1, \dots, T_n$, implements $T = T_n \circ \dots \circ T_1$. 

Note: Gradient functions for the ComposedMap class require many intermediate evaluations $T_k \circ \dots \circ T_1(x)$ for  $k \le n$. Currently, when these evaluations are needed we recompute them (rather than storing them), which gets slow for large $n$. The plan is to implement checkpointing (i.e., storing $T_k \circ \dots \circ T_1(x)$ for different $k$ to reduce cost of re-computation).

2022-09-22 17:02 UTC, mparno requested changes
Overall this looks good.  I have a few minor requests that will be needed to compile the code with a GPU backend, but everything should be ready to merge when those are addressed.

2022-09-22 19:09 UTC, michael-c-brennan commented on src/IdentityMap.cpp
> +    for(unsigned int i=0; i<int(this->inputDim - this->outputDim); ++i)
Fixed!

2022-09-22 19:09 UTC, michael-c-brennan commented on MParT/ConditionalMapBase.h
> +        friend class ComposedMap<MemorySpace>;
Fixed!

2022-09-22 19:09 UTC, michael-c-brennan commented on MParT/TriangularMap.h
> +    virtual void WrapCoeffs(Kokkos::View<double*, Kokkos::HostSpace> coeffs) override;
Fixed!

2022-09-22 19:09 UTC, michael-c-brennan commented on src/IdentityMap.cpp
> +    for(unsigned int j=0; j<output.size(); ++j)
Fixed!

2022-09-22 19:09 UTC, michael-c-brennan commented on src/IdentityMap.cpp
> +    for(unsigned int i=0; i<output.extent(0); ++i)
Fixed!

2022-09-22 19:10 UTC, michael-c-brennan commented
@mparno I think I fixed everything.

2022-09-23 01:17 UTC, mparno approved these changes

2022-09-23 01:17 UTC, merged