Fix silent hang in map inversion.
MeasureTransport/MParT pull request #351
Opened 2023-10-17 21:02 UTC by mparno

We were running into issues where an initial bracket could not be found during the map inversion because the map was essentially flat.  In this situation, the inverse would just hang.  This PR changes the way error handling is done inside the bracketed inverse to avoid this silent hang.  It also adds a basic check to determine of the function we're tracking to bracket is essentially flat.

2023-10-17 22:05 UTC, dannys4 requested changes
Looks good and passes tests, but introduces a bunch of seemingly unnecessary comments that should probably be gutted. I'll be happy to merge after that though.

2023-10-17 22:05 UTC, dannys4 commented on MParT/MonotoneComponent.h
> +    // template<typename PointType, typename CoeffsType>
Working from an old branch? Not sure why this is here. Admittedly, I should've deleted the docstring as well (sorry).

2023-10-18 17:59 UTC, mparno commented on MParT/Utilities/RootFinding.h
> +            if((fabs((yub-ylb)/(xub-xlb))<1e-12)&&((xub-xlb)>10)){
Yes, it's mostly just a check to make sure that we've at least tried to take a few steps.

2023-10-18 20:15 UTC, dannys4 approved these changes
lgtm

2023-10-18 20:15 UTC, merged