Add BasisEvaluator to MultivariateExpansionWorker
MeasureTransport/MParT pull request #358
Opened 2023-11-06 14:38 UTC by dannys4

This adds a type `BasisEvaluator` which adds another layer of indirection within `MultivariateExpansionWorker` and yet another template parameter. Basically, the idea is that the previous iteration had member `basis1d`, which treated all of the dimensions the same. Now, instead of storing the basis itself, the expansion worker stores a templated type that accesses the basis depending on its "homogeneity". If you have a homogeneous basis (e.g., you want to use Hermite polynomials in every input), then this reverts to the previous behavior. However, for obvious reasons, we might want an expansion with a strictly monotone basis in the diagonal by construction (e.g. polynomials for $x_{1:d-1}$ and sigmoids/iRBFs on $x_d$), but we don't want to lose any efficiency (and want to reuse the same "cache parameterization concept" implementation).

Along these lines, I had to re-pioneer the sigmoid class to be equivalent to a polynomial evaluator, where they were a PFB child class before. This tests that you can create a `OffdiagHomogeneous` map with sigmoids on the diagonal and polynomials off the diagonal. In a coming PR, I'll either add a wrapper type around Sigmoid1d for soft linear tails and a constant offset plus an interface for creating a sigmoid-based map.

Also, I definitely recommend squashing this PR bc I made a new file in this branch for TPF early on and then scrapped it :sweat_smile: .

2023-11-07 14:30 UTC, mparno commented
Hey @dannys4 !  This is going to be great.  I'll do a more thorough review before we merge, but could you also report on how this impacts evaluation speed?  Hopefully it doesn't have any impact, but I think it would be good to double check that.  We have the MParT-Speedtest repo that should serve as good starting point.   Thanks!

2023-11-13 20:19 UTC, dannys4 commented
So I ran the same benchmarks as included in the repo on a local machine (I tried doing the proper benchmarking things, quiescing the system, using taskset for the threads, etc). I put up the code I used to run it on a [fork of Speedtest](https://github.com/dannys4/MParT-SpeedTests), in a separate branch to remove CUDA.

How's this look for "no overhead":
![image](https://github.com/MeasureTransport/MParT/assets/43151183/470cfeb5-546f-476c-858d-7691b365d481)

2023-11-20 18:02 UTC, mparno requested changes
Thanks Danny!  Overall I think this looks great.  It definitely provides a much needed level of flexibility to our basis function definitions.   I added a few comments, but they should be pretty minor.  Let me know if you have questions or disagree.

2023-11-20 18:15 UTC, dannys4 commented on MParT/MultivariateExpansionWorker.h
> +enum BasisHomogeneity {Homogeneous, OffdiagHomogeneous, Heterogeneous};
+1 on this. Wasn't sure because of the "helper" classes moved to the top of this file and just went with one convention.

2023-11-20 18:15 UTC, dannys4 commented on MParT/MultivariateExpansionWorker.h
> +struct BasisEvaluator {
I'll address a few of these comments here: in the style guide I generally adhere to for C++, it's bad form to give an argument a name if you don't use it in the function (I think this is supposed to help with confusing globals? I'm actually not sure now that I think about it). Regardless of whether I name these things, I need to create documentation on all of these functions that could render in the doxygen similar to ConditionalMapBase etc.

2023-11-20 18:15 UTC, dannys4 commented on MParT/MultivariateExpansionWorker.h
> +struct BasisEvaluator<BasisHomogeneity::Heterogeneous, std::vector<std::shared_ptr<CommonBasisEvaluatorType>>> {
I completely agree with both of these points; see [my comment here](https://github.com/orgs/MeasureTransport/discussions/356#discussioncomment-7382225) on the design of this class. Basically, as far as I can tell, I need to either implement a crazy type erasure thing here without upgrading to C++20. There's really no good solution here unless we have concepts/variants--unless you have a better idea, how would I even create a class that works on GPU which can have an arbitrary number of callable objects without pointers? I guess I could use raw pointers, but everywhere else we use raw pointers, the memory the pointers point to is managed by Kokkos view; here, the pointers would be to functions or functors.

Anyway, since no one was clammoring for a heterogeneous basis in general, I figured this would be fine until someone decided to put up a type erasure PR.

2023-11-20 20:53 UTC, mparno commented on MParT/MultivariateExpansionWorker.h
> +struct BasisEvaluator<BasisHomogeneity::Heterogeneous, std::vector<std::shared_ptr<CommonBasisEvaluatorType>>> {
I think we could avoid type erasure using some variadic template trickery.  As a proof-of-concept, check out the example below.  It creates a basis evaluator for a 7 dimensional space.  The first and last dimensions use the same evaluator type (e.g., a HomogenousEvaluator in your context), dimensions 2-3 use the `EvaluatorType2` type, and dimensions 4-6 use the `EvaluatorType3` type.   Obviously this isn't a full implementation, but I think sketches out how we could go about it.   While the number of types needs to be known at compile time, the dimension of each type can vary at runtime.

```c++
#include <iostream>


template<int BasisIndex, typename... BasisTypes>
typename std::enable_if<BasisIndex >= sizeof...(BasisTypes), int>::type CountDim(std::tuple<BasisTypes...> const& bases){
    return 0;
}
template<int BasisIndex, typename... BasisTypes>
typename std::enable_if<BasisIndex < sizeof...(BasisTypes), int>::type CountDim(std::tuple<BasisTypes...> const& bases){
    return std::get<BasisIndex>(bases).dim() + CountDim<BasisIndex+1, BasisTypes...>(bases);
}

template<typename... BasisTypes>
struct BasisEvaluator {
    // dimension size, Basis evaluator

    BasisEvaluator(std::tuple<BasisTypes...> bases) : bases_(bases), dim_(CountDim<0,BasisTypes...>(bases))
    {
    }
    
    int dim(){return dim_;};

    // EvaluateAll(dim, output, max_order, input)
    void EvaluateAll(int d, double* output, int max_order, double input) const {
        EvaluateAllTemplate<0>(0, d, output, max_order, input);
    }
   
    template<int BasisIndex>
    typename std::enable_if<BasisIndex < sizeof...(BasisTypes), void>::type EvaluateAllTemplate(int startDim, int d, double* output, int max_order, double input) const{
        
        int endDim = startDim + std::get<BasisIndex>(bases_).dim();
        if(d<endDim){
            std::get<BasisIndex>(bases_).EvaluateAll(d-startDim, output, max_order, input);
        }else{
            EvaluateAllTemplate<BasisIndex+1>(endDim,  d, output, max_order, input);
        }
    }
    template<int BasisIndex>
    typename std::enable_if<BasisIndex == sizeof...(BasisTypes), void>::type EvaluateAllTemplate(int startDim, int d, double* output, int max_order, double input) const{
        throw std::runtime_error("Invalid index provided to BasisEvaluate::EvaluateAll.");
    }
    



    int dim_;
    std::tuple<BasisTypes...> bases_;
};

// Helper function to make it easier to construct this type 
template<typename... BasisTypes>
BasisEvaluator<BasisTypes...> TensorProduct(BasisTypes... evaluators)
{
    return BasisEvaluator<BasisTypes...>( std::tuple<BasisTypes...>(evaluators...) );
}


struct EvaluatorType1 {
    
    int dim() const{return 1;};

    void EvaluateAll(int, double* output, int max_order, double input) const{
        output[0] = 1.0;
    }
};

struct EvaluatorType2 {

    int dim() const{return 3;};

    void EvaluateAll(int, double* output, int max_order, double input) const{
        output[0] = 2.0;
    }
};

struct EvaluatorType3 {

    int dim() const{return 2;};

    void EvaluateAll(int, double* output, int max_order, double input) const{
        output[0] = 3.0;
    }
};

int main(){

    EvaluatorType1 basis1;
    EvaluatorType2 basis2;
    EvaluatorType3 basis3;

    
    auto evaluator = TensorProduct(basis1, basis2, basis3, basis1);

    double output;
    for(int i=0; i<7; ++i){
        evaluator.EvaluateAll(i, &output, 1, 1);
        std::cout << "EvaluateAll(" << i << ") = " << output << std::endl;
    }

}
```

2023-11-21 00:13 UTC, dannys4 commented on MParT/MultivariateExpansionWorker.h
> +struct BasisEvaluator<BasisHomogeneity::Heterogeneous, std::vector<std::shared_ptr<CommonBasisEvaluatorType>>> {
I stared at this code for awhile convincing myself why it compiled and it seems like it makes sense after some careful thought and playing with Godbolt. Incredible thought on the recursive template pattern. I didn't realize you could do `<` and `>` in template metaprogramming! I will make a few notes:
- I'm concerned that this will make compilation time a nightmare and could be problematic for even small dimensions.
- [Tuples are not well-supported on GPU](https://github.com/kokkos/kokkos/issues/900). If we're allowing tuples, I'm not sure why shared ptr is offlimits.
- I thought we established in our adventures into adaptive quadrature that recursion on the GPU is not a great strategy. Similar to above-- if we're allowing recursion, I'm not sure why shared ptr is offlimits.

2023-11-21 14:24 UTC, mparno commented on MParT/MultivariateExpansionWorker.h
> +struct BasisEvaluator<BasisHomogeneity::Heterogeneous, std::vector<std::shared_ptr<CommonBasisEvaluatorType>>> {
These are good points Danny and definitely things to consider.  I'm not particularly concerned for the following reasons, but perhaps the next step is to (1) merge this with the vector of pointers, (2) run some tests to check performance and GPU compilation, and (3) decide if it's worth refactoring the vector-of-pointers code.

**Compilation Time**
How many different evaluator blocks do you think we'd use here?  If it's only a handful, then I wouldn't expect a huge compilation time.  This class doesn't have a lot of code of it's own that would need to be compiled for each change in template parameters and the template recursion should be relatively shallow unless there are applications with hundreds of different evaluator blocks.

**Tuples**
That link was discussing boost tuples and an implementation of tuples in Kokkos.  As of [CUDA 9.2](https://docs.nvidia.com/cuda/archive/9.2/cuda-toolkit-release-notes/index.html#cuda-compiler-new-features%5B/url%5D), tuples are natively supported in CUDA kernels so I don't expect any issues here.  Still, I can verify that this code will compile and run in a cuda kernel before we move forward.

**Recursion**
There is a big difference between this simple recursion and the adaptive recursion we were playing with for the quadrature.  First, the recursion has a known and relatively small depth here (the number of different evaluator blocks). This also isn't technically calling the same function recursively because the template parameters are different each time.  This is essentially just expanding the if statement in the `EvaluateAllTemplate`, which I suspect the compiler will be able to efficiently optimize.

2023-11-21 14:24 UTC, mparno commented on MParT/MultivariateExpansionWorker.h
> +struct BasisEvaluator {
Sounds good.  Readability was my biggest concern, which could be improved with names or docs, so I'm fine skipping the names and just adding some documentation.

2024-01-31 15:32 UTC, mparno approved these changes
Thanks Danny!

2024-01-31 15:41 UTC, merged